apiVersion: v1
kind: Service
metadata:
  name: existing-single-inrepo-port-ingress-autodeploy-20250820145812
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app: existing-single-inrepo-port-ingress-autodeploy-20250820145812
